--------------------------------------------------------
--  File created - Tuesday-May-21-2024   
--------------------------------------------------------
DROP TABLE "ALBUMES" CASCADE CONSTRAINTS;
DROP TABLE "ARTISTAS"  CASCADE CONSTRAINTS;
DROP TABLE "CANCIONES"  CASCADE CONSTRAINTS;
DROP TABLE "CANCIONES_EN_LISTA"  CASCADE CONSTRAINTS;
DROP TABLE "GENEROS"  CASCADE CONSTRAINTS;
DROP TABLE "LISTAS_DE_REPRODUCCION"  CASCADE CONSTRAINTS;
DROP TABLE "TIPOS_MEDIO"  CASCADE CONSTRAINTS;


--------------------------------------------------------
--  Craete tables
--------------------------------------------------------
CREATE TABLE "ALBUMES" ("ID" NUMBER, "TITULO" VARCHAR2(160 BYTE), "ARTISTA_ID" NUMBER);
CREATE TABLE "ARTISTAS" ("ID" NUMBER, "NOMBRE" VARCHAR2(120 BYTE));
CREATE TABLE "CANCIONES" ("ID" NUMBER, "NOMBRE" VARCHAR2(200 BYTE), "ALBUM_ID" NUMBER, "MEDIO_ID" NUMBER, "GENERO_ID" NUMBER, "COMPOSITOR" VARCHAR2(220 BYTE), "MILISEGUNDOS" NUMBER, "BYTES" NUMBER, "PRECIO_UNITARIO" NUMBER(10,2));
CREATE TABLE "CANCIONES_EN_LISTA" ("LISTA_ID" NUMBER, "CANCION_ID" NUMBER);
CREATE TABLE "GENEROS" ("ID" NUMBER, "NOMBRE" VARCHAR2(120 BYTE));
CREATE TABLE "LISTAS_DE_REPRODUCCION" ("ID" NUMBER, "NOMBRE" VARCHAR2(120 BYTE));
CREATE TABLE "TIPOS_MEDIO" ("ID" NUMBER, "NOMBRE" VARCHAR2(120 BYTE));


