--- Sentencias SQL para la creacion del esquema de MusiK

-- USO
-- Copie el contenido de este archivo en una pestania SQL de SQL Developer
-- Ejecutelo como un script - Utilice el boton correspondiente de la pestania utilizada

-- borrado de objetos

drop sequence musik_sequence;

drop table CANCIONES_EN_LISTA;
drop table CANCIONES;
drop table GENEROS;
drop table TIPOS_MEDIO;
drop table LISTAS_DE_REPRODUCCION;
drop table ALBUMES;
drop table ARTISTAS;



-- Creación del secuenciador
create sequence musik_sequence;



-- Creacion de la tabla ARTISTAS y especificación de sus restricciones
CREATE TABLE ARTISTAS 
(	ID NUMBER NOT NULL, 
	NOMBRE VARCHAR2(120 BYTE)
);
ALTER TABLE ARTISTAS ADD CONSTRAINT PK_Artista PRIMARY KEY (ID);


-- Creacion de la tabla ALBUMES y especificación de sus restricciones
CREATE TABLE ALBUMES
(	ID NUMBER NOT NULL, 
	TITULO VARCHAR2(160 BYTE) NOT NULL, 
	ARTISTA_ID NUMBER NOT NULL, 
	CONSTRAINT FK_ALBUMARTISTAID FOREIGN KEY (ARTISTA_ID) REFERENCES ARTISTAS (ID) ENABLE
);
ALTER TABLE ALBUMES ADD CONSTRAINT PK_Album PRIMARY KEY (ID);

-- Creacion de la tabla GENEROS y especificación de sus restricciones
CREATE TABLE GENEROS 
(	ID NUMBER NOT NULL, 
	NOMBRE VARCHAR2(120 BYTE)
);
ALTER TABLE GENEROS ADD CONSTRAINT PK_Genero PRIMARY KEY (ID);

-- Creacion de la tabla TIPOS_MEDIO y especificación de sus restricciones
CREATE TABLE TIPOS_MEDIO 
(	ID NUMBER NOT NULL, 
	NOMBRE VARCHAR2(120 BYTE)
); 
ALTER TABLE TIPOS_MEDIO ADD CONSTRAINT PK_Tipos_medio PRIMARY KEY (ID);

-- Creacion de la tabla CANCIONES y especificación de sus restricciones
CREATE TABLE CANCIONES
(	ID NUMBER NOT NULL, 
	NOMBRE VARCHAR2(200 BYTE) NOT NULL, 
	ALBUM_ID NUMBER, 
	MEDIO_ID NUMBER NOT NULL, 
	GENERO_ID NUMBER, 
	COMPOSITOR VARCHAR2(220 BYTE), 
	MILISEGUNDOS NUMBER NOT NULL, 
	BYTES NUMBER, 
	PRECIO_UNITARIO NUMBER(10,2) NOT NULL, 
	CONSTRAINT PK_Cancion PRIMARY KEY (ID)   
);


ALTER TABLE CANCIONES
ADD CONSTRAINT FK_Album_Id 
FOREIGN KEY (ALBUM_ID) REFERENCES ALBUMES (ID);

ALTER TABLE CANCIONES
ADD CONSTRAINT FK_Genero_Id 
FOREIGN KEY (GENERO_ID) REFERENCES GENEROS (ID);

ALTER TABLE CANCIONES
ADD CONSTRAINT FK_Medio_Id 
FOREIGN KEY (MEDIO_ID) REFERENCES TIPOS_MEDIO (ID);


-- Creacion de la tabla LISTAS_DE_REPRODUCCION y especificación de sus restricciones
CREATE TABLE LISTAS_DE_REPRODUCCION 
(	ID NUMBER NOT NULL, 
	NOMBRE VARCHAR2(120 BYTE)
);
ALTER TABLE LISTAS_DE_REPRODUCCION ADD CONSTRAINT PK_Lista PRIMARY KEY (ID);

-- Creacion de la tabla CANCIONES_EN_LISTA y especificación de sus restricciones
CREATE TABLE CANCIONES_EN_LISTA
(	LISTA_ID NUMBER NOT NULL, 
	CANCION_ID NUMBER NOT NULL, 
	CONSTRAINT FK_CANCION_ID FOREIGN KEY (CANCION_ID)
	REFERENCES CANCIONES (ID), 
	CONSTRAINT FK_LISTA_ID FOREIGN KEY (LISTA_ID)
	REFERENCES LISTAS_DE_REPRODUCCION (ID)
) ;
ALTER TABLE CANCIONES_EN_LISTA ADD CONSTRAINT PK_Canciones_en_lista PRIMARY KEY (LISTA_ID, CANCION_ID);



